// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3rVhAyWgA8hP5dGiNSvHrDpYnwiLuJQk',
    appId: '1:625972239288:web:997727416d9add9c200d4d',
    messagingSenderId: '625972239288',
    projectId: 'schedule-app-49956',
    authDomain: 'schedule-app-49956.firebaseapp.com',
    storageBucket: 'schedule-app-49956.firebasestorage.app',
    measurementId: 'G-1RPSXR9J5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7wj0ZccDbAewdPtMrNusdzoibn4BR-Mw',
    appId: '1:625972239288:android:bca2434ca21a3814200d4d',
    messagingSenderId: '625972239288',
    projectId: 'schedule-app-49956',
    storageBucket: 'schedule-app-49956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFY5Hv3IGsDiIly6GiAzAV0DyuPkyCKvg',
    appId: '1:625972239288:ios:2bb95a18c603d0cb200d4d',
    messagingSenderId: '625972239288',
    projectId: 'schedule-app-49956',
    storageBucket: 'schedule-app-49956.firebasestorage.app',
    iosBundleId: 'com.example.scheduleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFY5Hv3IGsDiIly6GiAzAV0DyuPkyCKvg',
    appId: '1:625972239288:ios:2bb95a18c603d0cb200d4d',
    messagingSenderId: '625972239288',
    projectId: 'schedule-app-49956',
    storageBucket: 'schedule-app-49956.firebasestorage.app',
    iosBundleId: 'com.example.scheduleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3rVhAyWgA8hP5dGiNSvHrDpYnwiLuJQk',
    appId: '1:625972239288:web:f04f99bf7a2959d9200d4d',
    messagingSenderId: '625972239288',
    projectId: 'schedule-app-49956',
    authDomain: 'schedule-app-49956.firebaseapp.com',
    storageBucket: 'schedule-app-49956.firebasestorage.app',
    measurementId: 'G-H5LH4ERHVS',
  );
}
