// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpNi3Uh5VHt1xwK9AEgUKFTikHUcrdLW4',
    appId: '1:986290678246:web:9a1ac50f512be41c868e27',
    messagingSenderId: '986290678246',
    projectId: 'schedule-app-1ecd4',
    authDomain: 'schedule-app-1ecd4.firebaseapp.com',
    storageBucket: 'schedule-app-1ecd4.firebasestorage.app',
    measurementId: 'G-TZL03WVSB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkfHG-BAx8TIAjmO8OusMCN7g8oNaw_14',
    appId: '1:986290678246:android:abe9c272f011a2b3868e27',
    messagingSenderId: '986290678246',
    projectId: 'schedule-app-1ecd4',
    storageBucket: 'schedule-app-1ecd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxq9QSu1TRd1q9CXultwn_y9tFZX73XqI',
    appId: '1:986290678246:ios:0201437839875d99868e27',
    messagingSenderId: '986290678246',
    projectId: 'schedule-app-1ecd4',
    storageBucket: 'schedule-app-1ecd4.firebasestorage.app',
    iosBundleId: 'com.example.scheduleApp',
  );
}
